export default {
  items: [],
  isLoading: true,
  loadingError: null,
  isPaymentConfirming: false,
  paymentConfirmingError: null,
  isAdRunning: false,
  adRunningError: null,
  isAdStopped: false,
  adStoppingError: null,
  isAdExpiring: false,
  adExpiringError: null,
  isOrderDeleting: false,
  orderDeletingError: null,
};
